# =====================================================================
#  Repair C:\php\8.3\php.ini  -  IFGF Church CMS
#
#  Fixes three defects from setup-windows.ps1 v2:
#    1. opcache was written as extension= but is a Zend extension.
#    2. mysqli was uncommented AND appended, so it loaded twice.
#    3. The extension list was hardcoded. Extensions with no matching
#       php_*.dll (bcmath and friends are compiled into php.exe on
#       Windows) produced "Unable to load dynamic library" warnings.
#
#  This script rebuilds php.ini from php.ini-development and enables
#  ONLY extensions whose DLL actually exists on disk. Idempotent - safe
#  to run repeatedly. Elevation needed only if PHP is under Program Files.
#
#     .\tools\fix-php-ini.ps1
# =====================================================================

[CmdletBinding()]
param(
    [string]$PhpRoot = 'C:\php\8.3'
)

$ErrorActionPreference = 'Stop'

function Section($t) {
    Write-Host ''
    Write-Host ('=' * 70) -ForegroundColor DarkCyan
    Write-Host "  $t" -ForegroundColor Cyan
    Write-Host ('=' * 70) -ForegroundColor DarkCyan
}

Section "Repairing php.ini in $PhpRoot"

$ini      = Join-Path $PhpRoot 'php.ini'
$template = Join-Path $PhpRoot 'php.ini-development'
$extDir   = Join-Path $PhpRoot 'ext'

if (-not (Test-Path $template)) { throw "Not found: $template  (is `$PhpRoot correct?)" }
if (-not (Test-Path $extDir))   { throw "Not found: $extDir" }

# --- what is actually on disk ----------------------------------------
$available = Get-ChildItem "$extDir\php_*.dll" -ErrorAction SilentlyContinue |
             ForEach-Object { $_.BaseName -replace '^php_', '' } |
             Sort-Object

Write-Host "  $($available.Count) extension DLLs present in ext\" -ForegroundColor Green
Write-Host "  $($available -join ', ')" -ForegroundColor DarkGray

# --- what this project wants -----------------------------------------
# Regular extensions. Anything here without a DLL is compiled into
# php.exe on Windows and needs no line at all.
$wanted = @('bcmath','curl','exif','fileinfo','gd','intl','mbstring',
            'openssl','pdo_mysql','mysqli','pdo_sqlite','sqlite3',
            'sodium','zip')

$toEnable = $wanted | Where-Object { $available -contains $_ }
$builtIn  = $wanted | Where-Object { $available -notcontains $_ }

Write-Host ''
Write-Host "  Enabling ($($toEnable.Count)): $($toEnable -join ', ')" -ForegroundColor Green
if ($builtIn) {
    Write-Host "  No DLL, assumed compiled in: $($builtIn -join ', ')" -ForegroundColor Yellow
}

# --- rebuild from the pristine template ------------------------------
if (Test-Path $ini) {
    $backup = "$ini.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
    Copy-Item $ini $backup
    Write-Host ''
    Write-Host "  Backed up existing php.ini -> $(Split-Path -Leaf $backup)" -ForegroundColor DarkGray
}

$c = Get-Content $template -Raw

# Never leave a stale/duplicated directive behind: strip every
# extension/zend_extension/extension_dir line, then write one clean block.
$c = $c -replace '(?m)^\s*;?\s*(zend_)?extension\s*=.*$', ''
$c = $c -replace '(?m)^\s*;?\s*extension_dir\s*=.*$', ''

$block = @"

; ===================================================================
;  IFGF Church CMS - generated by tools\fix-php-ini.ps1
;  Only extensions with a real DLL in ext\ are listed here.
; ===================================================================
extension_dir = "$extDir"

"@
foreach ($e in $toEnable) { $block += "extension=$e`r`n" }

# opcache is a ZEND extension - this was the "Invalid library" warning.
if ($available -contains 'opcache') {
    $block += "`r`nzend_extension=opcache`r`n"
}

$block += @"

; --- IFGF development settings -------------------------------------
memory_limit = 512M
max_execution_time = 300
date.timezone = Asia/Taipei
"@

Set-Content -Path $ini -Value ($c.TrimEnd() + "`r`n" + $block) -Encoding ASCII
Write-Host "  Wrote $ini" -ForegroundColor Green

# --- verify -----------------------------------------------------------
Section 'Verification'

$php = Join-Path $PhpRoot 'php.exe'

Write-Host '  php -v' -ForegroundColor Cyan
& $php -v 2>&1 | Select-Object -First 4

Write-Host ''
Write-Host '  Startup warnings:' -ForegroundColor Cyan
$warn = & $php -r "echo 'ok';" 2>&1 | Where-Object { $_ -match 'Warning|Fatal|Unable|Invalid' }
if ($warn) { $warn | ForEach-Object { Write-Host "    $_" -ForegroundColor Red } }
else       { Write-Host '    none' -ForegroundColor Green }

# The full set required by the 183 packages in composer.lock.
$required = @(
    'bcmath','ctype','curl','dom','exif','fileinfo','filter','gd','hash',
    'iconv','json','libxml','mbstring','openssl','pcre','pdo','pdo_mysql',
    'phar','session','simplexml','sodium','tokenizer','xml','xmlreader',
    'xmlwriter','zip','zlib'
)
$loaded  = (& $php -m 2>$null) | ForEach-Object { $_.Trim().ToLower() } |
           Where-Object { $_ -and $_ -notmatch '^\[' }
$missing = $required | Where-Object { $loaded -notcontains $_ }

Write-Host ''
Write-Host "  Modules loaded: $($loaded.Count)" -ForegroundColor Cyan
if ($missing.Count -eq 0) {
    Write-Host '  All 27 required extensions present.' -ForegroundColor Green
} else {
    Write-Host "  STILL MISSING: $($missing -join ', ')" -ForegroundColor Red
    Write-Host '  Paste this line back.' -ForegroundColor Yellow
}

Write-Host ''
Write-Host '  Next:  .\tools\setup-windows.ps1 -SkipInstall' -ForegroundColor Magenta
Write-Host ''
